graph LR
  subgraph legend
    direction LR
    x7420bd9270f8d27d([""Up to date""]):::uptodate --- xf0bce276fe2b9d3e>""Function""]:::none
    xf0bce276fe2b9d3e>""Function""]:::none --- x5bffbffeae195fc9{{""Object""}}:::none
  end
  subgraph Graph
    direction LR
    xb42d9a5e1b0024d9>"grabSystemIndex"]:::uptodate --> x925445b64f5515ad>"combine_metadata_with_pulls"]:::uptodate
    x3085da0c12f08617>"grabRowid"]:::uptodate --> x925445b64f5515ad>"combine_metadata_with_pulls"]:::uptodate
    xbd672cf7550f2af2>"load_points_add_NHD_info"]:::uptodate --> xbd672cf7550f2af2>"load_points_add_NHD_info"]:::uptodate
    x5b61bf087fabd667>"points_to_csv"]:::uptodate --> x5b61bf087fabd667>"points_to_csv"]:::uptodate
    x8a2822f6635bd6b5>"collate_csvs_from_drive"]:::uptodate --> x8a2822f6635bd6b5>"collate_csvs_from_drive"]:::uptodate
    xec0704e9d53864a1{{"p1_targets_list"}}:::uptodate --> xec0704e9d53864a1{{"p1_targets_list"}}:::uptodate
    x81eb2ab69a337002>"get_AOI_centers"]:::uptodate --> x81eb2ab69a337002>"get_AOI_centers"]:::uptodate
    x6bc791ebaeaec04f>"calculate_8_7_handoff"]:::uptodate --> x6bc791ebaeaec04f>"calculate_8_7_handoff"]:::uptodate
    x4e5b18507a4933f4{{"p2_targets_list"}}:::uptodate --> x4e5b18507a4933f4{{"p2_targets_list"}}:::uptodate
    xaf07a05bf3aaf1b9>"get_hucs_from_points"]:::uptodate --> xaf07a05bf3aaf1b9>"get_hucs_from_points"]:::uptodate
    xe6114c4964b2ed63>"download_csvs_from_drive"]:::uptodate --> xe6114c4964b2ed63>"download_csvs_from_drive"]:::uptodate
    x251b431606ed97b5{{"p0_targets_list"}}:::uptodate --> x251b431606ed97b5{{"p0_targets_list"}}:::uptodate
    xdcbbc71ec73ed665>"baseline_QAQC_RS_data"]:::uptodate --> xdcbbc71ec73ed665>"baseline_QAQC_RS_data"]:::uptodate
    xb6046b564c2b17c1>"select_polygons_by_points"]:::uptodate --> xb6046b564c2b17c1>"select_polygons_by_points"]:::uptodate
    xaf703f04ade75c35>"calculate_9_8_handoff"]:::uptodate --> xaf703f04ade75c35>"calculate_9_8_handoff"]:::uptodate
    xff8a2b0e00f078a5>"calculate_5_7_handoff"]:::uptodate --> xff8a2b0e00f078a5>"calculate_5_7_handoff"]:::uptodate
    x31c12dca6242a905>"collate_handoff_coefficients"]:::uptodate --> x31c12dca6242a905>"collate_handoff_coefficients"]:::uptodate
    xfbf236c5a2d16b7f>"combine_and_simplify_sfs"]:::uptodate --> xfbf236c5a2d16b7f>"combine_and_simplify_sfs"]:::uptodate
    x40d3e75e836ff0df>"apply_handoffs"]:::uptodate --> x40d3e75e836ff0df>"apply_handoffs"]:::uptodate
    xb652901ed2431f5d{{"p3_targets_list"}}:::uptodate --> xb652901ed2431f5d{{"p3_targets_list"}}:::uptodate
    xb8b66377ce03c48e>"calculate_7_8_handoff"]:::uptodate --> xb8b66377ce03c48e>"calculate_7_8_handoff"]:::uptodate
    x381670d2b9b2e829>"get_polygons"]:::uptodate --> x381670d2b9b2e829>"get_polygons"]:::uptodate
  end
  classDef uptodate stroke:#000000,color:#ffffff,fill:#354823;
  classDef none stroke:#000000,color:#000000,fill:#94a4ac;
  linkStyle 0 stroke-width:0px;
  linkStyle 1 stroke-width:0px;
  linkStyle 4 stroke-width:0px;
  linkStyle 5 stroke-width:0px;
  linkStyle 6 stroke-width:0px;
  linkStyle 7 stroke-width:0px;
  linkStyle 8 stroke-width:0px;
  linkStyle 9 stroke-width:0px;
  linkStyle 10 stroke-width:0px;
  linkStyle 11 stroke-width:0px;
  linkStyle 12 stroke-width:0px;
  linkStyle 13 stroke-width:0px;
  linkStyle 14 stroke-width:0px;
  linkStyle 15 stroke-width:0px;
  linkStyle 16 stroke-width:0px;
  linkStyle 17 stroke-width:0px;
  linkStyle 18 stroke-width:0px;
  linkStyle 19 stroke-width:0px;
  linkStyle 20 stroke-width:0px;
  linkStyle 21 stroke-width:0px;
  linkStyle 22 stroke-width:0px;
  linkStyle 23 stroke-width:0px;
