graph LR
  subgraph legend
    direction LR
    x7420bd9270f8d27d([""Up to date""]):::uptodate --- x0a52b03877696646([""Outdated""]):::outdated
    x0a52b03877696646([""Outdated""]):::outdated --- xbf4603d6c2c2ad6b([""Stem""]):::none
    xbf4603d6c2c2ad6b([""Stem""]):::none --- x70a5fa6bea6f298d[""Pattern""]:::none
    x70a5fa6bea6f298d[""Pattern""]:::none --- xf0bce276fe2b9d3e>""Function""]:::none
    xf0bce276fe2b9d3e>""Function""]:::none --- x5bffbffeae195fc9{{""Object""}}:::none
  end
  subgraph Graph
    direction LR
    x52d7162f39f48bed>"collate_DSWE1_corrected_files"]:::uptodate --> x1a19470de33ec9f3(["d_combined_DSWE1_corrected"]):::uptodate
    x58cff6901aa6ed85["d_DSWE1_handoffs_to7"]:::uptodate --> x1a19470de33ec9f3(["d_combined_DSWE1_corrected"]):::uptodate
    x761e1ea536cacd68["d_DSWE1_handoffs_to8"]:::uptodate --> x1a19470de33ec9f3(["d_combined_DSWE1_corrected"]):::uptodate
    xc9f6442815764be2(["c_DSWE1_regional_file_file"]):::uptodate --> xc8ba0bedc1022d0b(["c_DSWE1_regional_file"]):::uptodate
    x8e2d5d897ade3bd6(["a_NW_CLP_polygons_file"]):::uptodate --> x1e096aa97ed6fcf9(["a_NW_CLP_polygons"]):::uptodate
    x0bbb24374591c2d4(["b_collated_historical_NW_CLP"]):::uptodate --> x2d9d3921e79efd08(["b_combined_NW_CLP_metadata_data"]):::uptodate
    x925445b64f5515ad>"combine_metadata_with_pulls"]:::uptodate --> x2d9d3921e79efd08(["b_combined_NW_CLP_metadata_data"]):::uptodate
    x94109a458fab8f77(["a_CLP_polygons_file"]):::uptodate --> x19dc28c47baa7e4a(["a_CLP_polygons"]):::uptodate
    x2210298be09f2fd9(["a_make_collated_points"]):::uptodate --> x8ce140145db15f6c(["a_collated_points_file"]):::uptodate
    x381670d2b9b2e829>"get_polygons"]:::uptodate --> x664dd0b8ce3dd77f(["a_make_CLP_polygon"]):::uptodate
    x1e096aa97ed6fcf9(["a_NW_CLP_polygons"]):::uptodate --> x0fa5015d30556ce3(["a_make_NW_CLP_centers"]):::uptodate
    xb115dc86c58dee32>"get_POI_centers"]:::uptodate --> x0fa5015d30556ce3(["a_make_NW_CLP_centers"]):::uptodate
    x8ce140145db15f6c(["a_collated_points_file"]):::uptodate --> xc538bed230e0fa75(["a_collated_points"]):::uptodate
    x7a05bf85313debd2(["a_NW_CLP_centers"]):::uptodate --> x2210298be09f2fd9(["a_make_collated_points"]):::uptodate
    x01bfdce7c5366867(["a_NW_station_points"]):::uptodate --> x2210298be09f2fd9(["a_make_collated_points"]):::uptodate
    xfbf236c5a2d16b7f>"combine_and_simplify_sfs"]:::uptodate --> x2210298be09f2fd9(["a_make_collated_points"]):::uptodate
    xc538bed230e0fa75(["a_collated_points"]):::uptodate --> x01fe2ce78e8a07a2(["a_collated_pts_to_csv"]):::uptodate
    x5b61bf087fabd667>"points_to_csv"]:::uptodate --> x01fe2ce78e8a07a2(["a_collated_pts_to_csv"]):::uptodate
    x95df79a67bf96baa(["b_downloaded_historical_NW_CLP"]):::uptodate --> x0bbb24374591c2d4(["b_collated_historical_NW_CLP"]):::uptodate
    x8a2822f6635bd6b5>"collate_csvs_from_drive"]:::uptodate --> x0bbb24374591c2d4(["b_collated_historical_NW_CLP"]):::uptodate
    x664dd0b8ce3dd77f(["a_make_CLP_polygon"]):::uptodate --> x94109a458fab8f77(["a_CLP_polygons_file"]):::uptodate
    x85e5557d30e57bd4(["c_5_9_band_list"]):::uptodate --> xee7e7b8e3ec490a0["c_regional_7_8_handoff"]:::uptodate
    xc8ba0bedc1022d0b(["c_DSWE1_regional_file"]):::uptodate --> xee7e7b8e3ec490a0["c_regional_7_8_handoff"]:::uptodate
    xb8b66377ce03c48e>"calculate_7_8_handoff"]:::uptodate --> xee7e7b8e3ec490a0["c_regional_7_8_handoff"]:::uptodate
    xd84caa00dd9cc327(["b_collated_files"]):::uptodate --> xb44148556a3db616["b_QAQC_filtered_data"]:::uptodate
    xdcbbc71ec73ed665>"baseline_QAQC_RS_data"]:::uptodate --> xb44148556a3db616["b_QAQC_filtered_data"]:::uptodate
    xb44148556a3db616["b_QAQC_filtered_data"]:::uptodate --> xc9f6442815764be2(["c_DSWE1_regional_file_file"]):::uptodate
    x0c6bbb4fd9871db8(["c_make_collated_handoff_coefficients"]):::uptodate --> xf50c81ff8f09c8a6(["c_collated_handoff_coefficients_file"]):::uptodate
    xf1c19f624f3b39ba(["a_NW_station_points_file"]):::uptodate --> x01bfdce7c5366867(["a_NW_station_points"]):::uptodate
    x33a181fb2861cfe2(["a_NW_CLP_centers_file"]):::uptodate --> x7a05bf85313debd2(["a_NW_CLP_centers"]):::uptodate
    xca9a68b99721c1a0["a_get_NW_polygons"]:::uptodate --> x26fc033bf977f193(["a_NW_polygons_file"]):::uptodate
    xca7f1bf09c5d95d5>"apply_handoffs_to7"]:::uptodate --> x58cff6901aa6ed85["d_DSWE1_handoffs_to7"]:::uptodate
    x0cd988d6892f5a88(["c_collated_handoff_coefficients"]):::uptodate --> x58cff6901aa6ed85["d_DSWE1_handoffs_to7"]:::uptodate
    x0af3e3ea0c80e86e(["d_filtered_DSWE1_data"]):::uptodate --> x58cff6901aa6ed85["d_DSWE1_handoffs_to7"]:::uptodate
    xecce09bcfe077974>"apply_handoffs_to8"]:::uptodate --> x761e1ea536cacd68["d_DSWE1_handoffs_to8"]:::uptodate
    x0cd988d6892f5a88(["c_collated_handoff_coefficients"]):::uptodate --> x761e1ea536cacd68["d_DSWE1_handoffs_to8"]:::uptodate
    x0af3e3ea0c80e86e(["d_filtered_DSWE1_data"]):::uptodate --> x761e1ea536cacd68["d_DSWE1_handoffs_to8"]:::uptodate
    x85e5557d30e57bd4(["c_5_9_band_list"]):::uptodate --> x1ed050c4bc26fe64["c_regional_8_7_handoff"]:::uptodate
    xc8ba0bedc1022d0b(["c_DSWE1_regional_file"]):::uptodate --> x1ed050c4bc26fe64["c_regional_8_7_handoff"]:::uptodate
    x6bc791ebaeaec04f>"calculate_8_7_handoff"]:::uptodate --> x1ed050c4bc26fe64["c_regional_8_7_handoff"]:::uptodate
    x01b6d58d95b44267(["d_DSWE1_corrected_file_list"]):::uptodate --> xa64339db19e94847["d_Rrs_DSWE1_correction_figures"]:::uptodate
    xf5f2b7c5daf11e04>"make_Rrs_correction_figures"]:::uptodate --> xa64339db19e94847["d_Rrs_DSWE1_correction_figures"]:::uptodate
    x6d47e242f5ffd1c3(["a_make_NW_CLP_polygons"]):::uptodate --> x8e2d5d897ade3bd6(["a_NW_CLP_polygons_file"]):::uptodate
    xb44148556a3db616["b_QAQC_filtered_data"]:::uptodate --> x85e5557d30e57bd4(["c_5_9_band_list"]):::uptodate
    xf3865de35aeb5a5f(["c_8_9_band_list"]):::uptodate --> x9003abff127b994a["c_regional_9_8_handoff"]:::uptodate
    xc8ba0bedc1022d0b(["c_DSWE1_regional_file"]):::uptodate --> x9003abff127b994a["c_regional_9_8_handoff"]:::uptodate
    xaf703f04ade75c35>"calculate_9_8_handoff"]:::uptodate --> x9003abff127b994a["c_regional_9_8_handoff"]:::uptodate
    x26fc033bf977f193(["a_NW_polygons_file"]):::uptodate --> xe8cad48701564837(["a_NW_polygons"]):::uptodate
    x85e5557d30e57bd4(["c_5_9_band_list"]):::uptodate --> x35b0308127274134["c_regional_5_7_handoff"]:::uptodate
    xc8ba0bedc1022d0b(["c_DSWE1_regional_file"]):::uptodate --> x35b0308127274134["c_regional_5_7_handoff"]:::uptodate
    xff8a2b0e00f078a5>"calculate_5_7_handoff"]:::uptodate --> x35b0308127274134["c_regional_5_7_handoff"]:::uptodate
    x01fe2ce78e8a07a2(["a_collated_pts_to_csv"]):::uptodate --> x6095b08d9049a966(["a_collated_pts_file_file"]):::uptodate
    x0fa5015d30556ce3(["a_make_NW_CLP_centers"]):::uptodate --> x33a181fb2861cfe2(["a_NW_CLP_centers_file"]):::uptodate
    xeb5d928c060d1b77(["b_downloaded_historical_regional"]):::uptodate --> x98e603624261d973(["b_collated_historical_regional"]):::uptodate
    x8a2822f6635bd6b5>"collate_csvs_from_drive"]:::uptodate --> x98e603624261d973(["b_collated_historical_regional"]):::uptodate
    x44fb086f7f260822(["a_collated_pts_file"]):::uptodate --> xeb5d928c060d1b77(["b_downloaded_historical_regional"]):::uptodate
    xe6114c4964b2ed63>"download_csvs_from_drive"]:::uptodate --> xeb5d928c060d1b77(["b_downloaded_historical_regional"]):::uptodate
    xe8cad48701564837(["a_NW_polygons"]):::uptodate --> x7c4f8cf854f398db(["a_make_NW_station_points"]):::uptodate
    x76905cddb9d607bd(["a_NW_station_locs"]):::uptodate --> x7c4f8cf854f398db(["a_make_NW_station_points"]):::uptodate
    xbd672cf7550f2af2>"load_points_add_NHD_info"]:::uptodate --> x7c4f8cf854f398db(["a_make_NW_station_points"]):::uptodate
    x2d9d3921e79efd08(["b_combined_NW_CLP_metadata_data"]):::uptodate --> xd84caa00dd9cc327(["b_collated_files"]):::uptodate
    xaaa81e43adeadb29(["b_combined_regional_metadata_data"]):::uptodate --> xd84caa00dd9cc327(["b_collated_files"]):::uptodate
    x7c4f8cf854f398db(["a_make_NW_station_points"]):::uptodate --> xf1c19f624f3b39ba(["a_NW_station_points_file"]):::uptodate
    xef9615d7cfb4d5c6(["a_NW_locs_file_file"]):::uptodate --> xd19814a263acac59(["a_NW_locs_file"]):::uptodate
    x98e603624261d973(["b_collated_historical_regional"]):::uptodate --> xaaa81e43adeadb29(["b_combined_regional_metadata_data"]):::uptodate
    x925445b64f5515ad>"combine_metadata_with_pulls"]:::uptodate --> xaaa81e43adeadb29(["b_combined_regional_metadata_data"]):::uptodate
    xb44148556a3db616["b_QAQC_filtered_data"]:::uptodate --> x0af3e3ea0c80e86e(["d_filtered_DSWE1_data"]):::uptodate
    x6095b08d9049a966(["a_collated_pts_file_file"]):::uptodate --> x44fb086f7f260822(["a_collated_pts_file"]):::uptodate
    x35b0308127274134["c_regional_5_7_handoff"]:::uptodate --> x0c6bbb4fd9871db8(["c_make_collated_handoff_coefficients"]):::uptodate
    xee7e7b8e3ec490a0["c_regional_7_8_handoff"]:::uptodate --> x0c6bbb4fd9871db8(["c_make_collated_handoff_coefficients"]):::uptodate
    x1ed050c4bc26fe64["c_regional_8_7_handoff"]:::uptodate --> x0c6bbb4fd9871db8(["c_make_collated_handoff_coefficients"]):::uptodate
    x9003abff127b994a["c_regional_9_8_handoff"]:::uptodate --> x0c6bbb4fd9871db8(["c_make_collated_handoff_coefficients"]):::uptodate
    x31c12dca6242a905>"collate_handoff_coefficients"]:::uptodate --> x0c6bbb4fd9871db8(["c_make_collated_handoff_coefficients"]):::uptodate
    x2ac6a5009f306b06(["a_NW_station_locs_file"]):::uptodate --> x76905cddb9d607bd(["a_NW_station_locs"]):::uptodate
    xd19814a263acac59(["a_NW_locs_file"]):::uptodate --> x14d3cfb18cfecc06(["a_get_NW_hucs"]):::uptodate
    xaf07a05bf3aaf1b9>"get_hucs_from_points"]:::uptodate --> x14d3cfb18cfecc06(["a_get_NW_hucs"]):::uptodate
    xf50c81ff8f09c8a6(["c_collated_handoff_coefficients_file"]):::uptodate --> x0cd988d6892f5a88(["c_collated_handoff_coefficients"]):::uptodate
    x1cb344542dc83a1c["a_get_NW_NHD"]:::uptodate --> xca9a68b99721c1a0["a_get_NW_polygons"]:::uptodate
    xd19814a263acac59(["a_NW_locs_file"]):::uptodate --> xca9a68b99721c1a0["a_get_NW_polygons"]:::uptodate
    xb6046b564c2b17c1>"select_polygons_by_points"]:::uptodate --> xca9a68b99721c1a0["a_get_NW_polygons"]:::uptodate
    x14d3cfb18cfecc06(["a_get_NW_hucs"]):::uptodate --> xca9a68b99721c1a0["a_get_NW_polygons"]:::uptodate
    x44fb086f7f260822(["a_collated_pts_file"]):::uptodate --> x95df79a67bf96baa(["b_downloaded_historical_NW_CLP"]):::uptodate
    xe6114c4964b2ed63>"download_csvs_from_drive"]:::uptodate --> x95df79a67bf96baa(["b_downloaded_historical_NW_CLP"]):::uptodate
    xb44148556a3db616["b_QAQC_filtered_data"]:::uptodate --> xf3865de35aeb5a5f(["c_8_9_band_list"]):::uptodate
    x14d3cfb18cfecc06(["a_get_NW_hucs"]):::uptodate --> x1cb344542dc83a1c["a_get_NW_NHD"]:::uptodate
    x381670d2b9b2e829>"get_polygons"]:::uptodate --> x1cb344542dc83a1c["a_get_NW_NHD"]:::uptodate
    x1a19470de33ec9f3(["d_combined_DSWE1_corrected"]):::uptodate --> x01b6d58d95b44267(["d_DSWE1_corrected_file_list"]):::uptodate
    x19dc28c47baa7e4a(["a_CLP_polygons"]):::uptodate --> x6d47e242f5ffd1c3(["a_make_NW_CLP_polygons"]):::uptodate
    xe8cad48701564837(["a_NW_polygons"]):::uptodate --> x6d47e242f5ffd1c3(["a_make_NW_CLP_polygons"]):::uptodate
    xfbf236c5a2d16b7f>"combine_and_simplify_sfs"]:::uptodate --> x6d47e242f5ffd1c3(["a_make_NW_CLP_polygons"]):::uptodate
    xc071b53bbeee7133{{"b_targets_list"}}:::outdated --> xc071b53bbeee7133{{"b_targets_list"}}:::outdated
    x4896b865d128ba02{{"c_targets_list"}}:::outdated --> x4896b865d128ba02{{"c_targets_list"}}:::outdated
    xc96dc9257309fcea{{"a_targets_list"}}:::outdated --> xc96dc9257309fcea{{"a_targets_list"}}:::outdated
    xd6ab06fb3bbda539{{"d_targets_list"}}:::outdated --> xd6ab06fb3bbda539{{"d_targets_list"}}:::outdated
  end
  classDef uptodate stroke:#000000,color:#ffffff,fill:#354823;
  classDef outdated stroke:#000000,color:#000000,fill:#78B7C5;
  classDef none stroke:#000000,color:#000000,fill:#94a4ac;
  linkStyle 0 stroke-width:0px;
  linkStyle 1 stroke-width:0px;
  linkStyle 2 stroke-width:0px;
  linkStyle 3 stroke-width:0px;
  linkStyle 4 stroke-width:0px;
  linkStyle 95 stroke-width:0px;
  linkStyle 96 stroke-width:0px;
  linkStyle 97 stroke-width:0px;
  linkStyle 98 stroke-width:0px;
